server:
  port: 9090
rocketmq:
  producer:
    is-on-off: on
    group-name: hmop
    namesrv-addr: 10.5.28.28:9876
    max-message-size: 4096
    send-msg-timeout: 30000
    retry-times-when-send-failed: 2
  consumer:
    is-on-off: on
    group-name: hmop
    namesrv-addr: 10.5.28.28:9876
    topics: test_topic~*
    consume-thread-min: 20
    consume-thread-max: 64
    consume-message-batch-max-size: 1
