server.port=9090
#rocketmq
###producer
#??????????
rocketmq.producer.isOnOff=on
#??????????????group?????,????????rocketmq???ip@pid(pid??jvm??)??????
rocketmq.producer.groupName=hmop
#mq?nameserver??,????????????127.0.0.1:9876;127.0.0.1:9877
rocketmq.producer.namesrvAddr=10.5.28.28:9876
#?????? ??1024*4(4M)
rocketmq.producer.maxMessageSize=4096
#????????,??3000
rocketmq.producer.sendMsgTimeout=30000
#?????????????2
rocketmq.producer.retryTimesWhenSendFailed=2
###consumer
##??????????
rocketmq.consumer.isOnOff=on
rocketmq.consumer.groupName=hmop
#mq?nameserver??
rocketmq.consumer.namesrvAddr=10.5.28.28:9876
#??????????tags("*"????????????tags),???topic~tag1||tag2||tag3;topic2~*;
rocketmq.consumer.topics=test_topic~*;
rocketmq.consumer.consumeThreadMin=20
rocketmq.consumer.consumeThreadMax=64
#???????????????1?
rocketmq.consumer.consumeMessageBatchMaxSize=1

spring.redis.port=6379
spring.redis.host=localhost
spring.redis.database=0


